name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.2'

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    
    - name: Configure bundler
      run: |
        bundle config set --local frozen false
        bundle config set --local without 'production'
    
    - name: Install dependencies
      run: bundle install
    
    - name: Run RSpec tests
      run: bundle exec rspec
    
    - name: Run Rubocop
      run: bundle exec rubocop

    - name: Check code coverage
      run: bundle exec rake coverage
    
    - name: Run the default task
      run: bundle exec rake
    
    - name: Build gem
      run: gem build *.gemspec